/*  Example using clipping to modify the spectrum of an audio signal
    and emphasise a tone generated by the difference in frequency of 2 waves,
    using Mozzi sonification library.

    Demonstrates the use of EventDelay(), rand() and fixed-point numbers.
    
    Note that an example using the newer FixMath paradigm is also available: Difference_Tone_FixMath.

    Circuit: Audio output on digital pin 9 on a Uno or similar, or
    DAC/A14 on Teensy 3.1, or
    check the README or http://sensorium.github.io/Mozzi/

   Mozzi documentation/API
   https://sensorium.github.io/Mozzi/doc/html/index.html

   Mozzi help/discussion/announcements:
   https://groups.google.com/forum/#!forum/mozzi-users

   Copyright 2012-2024 Tim Barrass and the Mozzi Team

   Mozzi is licensed under the GNU Lesser General Public Licence (LGPL) Version 2.1 or later.
*/

#include <MIDI.h>
#include <Mozzi.h>
#include <Oscil.h>
#include <EventDelay.h>
#include <mozzi_rand.h>
#include <mozzi_midi.h>
#include <tables/sin2048_int8.h>
#include <ADSR.h>

MIDI_CREATE_DEFAULT_INSTANCE();

// use: Oscil <table_size, update_rate> oscilName (wavetable), look in .h file of table #included above
Oscil <SIN2048_NUM_CELLS, MOZZI_AUDIO_RATE> aSin1(SIN2048_DATA); // sine wave sound source
Oscil <SIN2048_NUM_CELLS, MOZZI_AUDIO_RATE> aSin2(SIN2048_DATA); // sine wave sound source
Oscil <SIN2048_NUM_CELLS, MOZZI_AUDIO_RATE> aGain(SIN2048_DATA); // to fade audio signal in and out before waveshaping

// for scheduling note changes
EventDelay kChangeNoteDelay;

// audio frequency as Q16n16 fractional number
Q16n16 freq1 = Q8n0_to_Q16n16(440);

// envelope generator
ADSR <MOZZI_CONTROL_RATE, MOZZI_AUDIO_RATE> envelope;

#define LED 3 // shows if MIDI is being recieved

const char POT_PIN = 0; // set the input for the knob to analog pin 0
const char LDR_PIN = 1; // set the input for the knob to analog pin 0

byte harmonic = 12;
byte shimmer = 128;

void HandleNoteOn(byte channel, byte note, byte velocity) {
  freq1 = Q8n0_to_Q16n16(mtof(float(note)));

  //harmonic = rand((byte)12);
  //shimmer = rand((byte)255);
  Q16n16 harmonic_step = freq1/12;
  Q16n16 freq2difference = harmonic*harmonic_step;
  freq2difference += (harmonic_step*shimmer)>>11;
  Q16n16 freq2 = freq1-freq2difference;

 
  aSin1.setFreq_Q16n16(freq1);
  aSin2.setFreq_Q16n16(freq2); // set the frequency with a Q16n16 fractional number
  
  envelope.noteOn();
  digitalWrite(LED,HIGH);
}

void HandleNoteOff(byte channel, byte note, byte velocity) {
  envelope.noteOff();
  digitalWrite(LED,LOW);
}

void HandleControllChange(){};

void setup(){

  Serial.begin(115200);

  pinMode(LED, OUTPUT);

  // Connect the HandleNoteOn function to the library, so it is called upon reception of a NoteOn.
  MIDI.setHandleNoteOn(HandleNoteOn);  // Put only the name of the function
  MIDI.setHandleNoteOff(HandleNoteOff);  // Put only the name of the function
  MIDI.setHandleControlChange(HandleControllChange);

  // Initiate MIDI communications, listen to all channels (not needed with Teensy usbMIDI)
  MIDI.begin(MIDI_CHANNEL_OMNI);

  envelope.setADLevels(255,64);
  envelope.setTimes(10,200,500,200); // 10000 is so the note will sustain 10 seconds unless a noteOff comes

  startMozzi(); // :)
  
}


void updateControl(){
  harmonic = ((byte)mozziAnalogRead<8>(LDR_PIN))/21.3;
  shimmer = ((byte)mozziAnalogRead<8>(LDR_PIN));

  MIDI.read();
  envelope.update();

}


AudioOutput updateAudio(){
   int asig = (int)((((uint32_t) aSin1.next()+ aSin2.next())*(envelope.next()))>>3);
  return MonoOutput::fromAlmostNBit(9, asig).clip();
  //return MonoOutput::from16Bit((int) (envelope.next() * asig));
}


void loop(){
  audioHook(); // required here
}
